import Head from "next/head";
import {
  FaGithub,
  FaLinkedin,
  FaTwitter,
} from "react-icons/fa";

import Footer from "./Footer";
import LatestProjects from "./LatestProjects";
import Nav from "./Nav";

export default function Home() {
  return (
    <div className="bg-cust-black text-neutral-400">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="w-3/4 mx-auto">
        <section>
          <article className="flex flex-wrap justify-center">
            <div className="max-w-xl text-center mt-6">
              <h1 className="text-neutral-200 text-3xl">
                Yair Quintana <span className="text-base">@CernunnosYQ</span>
              </h1>
              <h2 className="text-xl mb-2">Developer Fullstack</h2>
              <p className="my-4">
                I'm a self-taught web developer from mexico city, my experience
                is with python and react but I'm not afraid to learn and
                experiment with new technologies.
              </p>
              <div className="flex justify-center py-2">
                <FaGithub
                  className="
                cursor-pointer mx-4 text-3xl
                hover:text-accent hover:shadow-md hover:shadow-accent"
                />
                <FaLinkedin
                  className="
                cursor-pointer mx-4 text-3xl
                hover:text-accent hover:shadow-md hover:shadow-accent"
                />
                <FaTwitter
                  className="
                cursor-pointer mx-4 text-3xl
                hover:text-accent hover:shadow-md hover:shadow-accent"
                />
              </div>
              <div className="rounded-full overflow-hidden max-w-xs mx-auto mt-12">
                <img
                  src="/crnns cuadrada.jpg"
                  alt="Yair Quintana"
                  className="object-contain"
                />
              </div>
            </div>
          </article>
        </section>
        <h1 className="w-full px-8 pt-16 -mb-2 text-2xl text-neutral-200">
          Latest Projects
        </h1>
        <LatestProjects className="m-auto" />
      </main>

      <Footer />
    </div>
  );
}
