import Head from 'next/head'
import { SiTailwindcss } from 'react-icons/si'
import { FaGithub, FaLinkedin, FaPython, FaReact, FaTwitter } from "react-icons/fa"

import Footer from './Footer'
import LatestProjects from './LatestProjects'
import Nav from './Nav'

export default function Home() {
  return (
    <div className='bg-cust-black text-neutral-400'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className='w-3/4 mx-auto'>
        <section>
          <article className="flex flex-wrap justify-center">
            <div className='max-w-xl text-center mt-6'>
              <h1 className='text-neutral-200 text-3xl'>Yair Quintana <span className='text-base'>@CernunnosYQ</span></h1>
              <h2 className='text-xl mb-2'>Developer Fullstack</h2>
              <p className='my-4'>
                Soy desarrollador web autodidacta de ciudad de méxico, mi experiencia es con python
                 y react pero no tengo miedo a aprender y experimentar con nuevas tecnologías.
              </p>
            <div className="flex justify-center py-2">
              <FaGithub className='
                cursor-pointer mx-4 text-3xl
                hover:text-accent' />
              <FaLinkedin className='
                cursor-pointer mx-4 text-3xl
                hover:text-accent' />
              <FaTwitter className='
                cursor-pointer mx-4 text-3xl
                hover:text-accent' />
            </div>
            <div className='rounded-full overflow-hidden max-w-xs mx-auto mt-12'>
              <img src="/crnns cuadrada.jpg" alt="Yair Quintana" className='object-contain' />
            </div>
            </div>
          </article>
        
        </section>
        <h1 className="w-full px-8 pt-16 -mb-2 text-2xl text-neutral-200">Latest Projects</h1>
        <LatestProjects className='m-auto' />
      </main>

      <Footer />
    </div>
  )
}
